mod cache;
mod exec;
mod policy;
mod rpc;
mod sandbox;

use std::env;
use std::path::Path;
use rpc::RpcServer;
use policy::PolicyEngine;

fn main() {
    let args: Vec<String> = env::args().collect();
    
    // Auto-detect project root or fall back to current working directory
    let project_root = env::var("RITSU_PROJECT_ROOT")
        .unwrap_or_else(|_| env::current_dir()
            .map(|p| p.to_string_lossy().to_string())
            .unwrap_or_else(|_| ".".to_string())
        );

    if args.len() > 1 {
        match args[1].as_str() {
            "check" => {
                // CLI check: run policy checks directly (useful for Git pre-commit hooks)
                let files = &args[2..];
                if files.is_empty() {
                    println!("No files provided for check.");
                    return;
                }
                
                let engine = PolicyEngine::new(Path::new(&project_root));
                let violations = engine.audit_files(files);
                
                if !violations.is_empty() {
                    eprintln!("❌ Ritsu Policy Violation Detected!");
                    for v in &violations {
                        eprintln!(
                            "[{}] {} line {}: {}",
                            v.severity.to_uppercase(),
                            v.file_path,
                            v.line_number,
                            v.message
                        );
                    }
                    std::process::exit(1);
                } else {
                    println!("✅ All policy gates passed.");
                }
            }
            "init" => {
                println!("Initializing Ritsu in project root: {}", project_root);
                let git_hooks_dir = Path::new(&project_root).join(".git").join("hooks");
                if !git_hooks_dir.exists() {
                    eprintln!("Error: .git/hooks directory not found. Is this a Git repository?");
                    std::process::exit(1);
                }

                let pre_commit_path = git_hooks_dir.join("pre-commit");
                
                // Determine absolute path to the ritsud executable dynamically
                let current_exe = env::current_exe().unwrap_or_else(|_| {
                    Path::new(&project_root).join("ritsud").join("target").join("release").join("ritsud")
                });
                let exe_str = current_exe.to_string_lossy();

                let hook_script = format!(
                    "#!/bin/sh\n\
                     # Ritsu pre-commit hook - auto-generated by ritsud\n\n\
                     STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.(ts|tsx|js|jsx|py|go|rs|sql)$')\n\n\
                     if [ -z \"$STAGED_FILES\" ]; then\n\
                         exit 0\n\
                     fi\n\n\
                     echo \"Running Ritsu pre-commit policy checks...\"\n\
                     \"{}\" check $STAGED_FILES\n",
                    exe_str
                );

                if let Err(e) = std::fs::write(&pre_commit_path, hook_script) {
                    eprintln!("Failed to write pre-commit hook: {}", e);
                    std::process::exit(1);
                }

                // Set executable permissions on Unix systems
                #[cfg(unix)]
                {
                    use std::os::unix::fs::PermissionsExt;
                    if let Ok(metadata) = std::fs::metadata(&pre_commit_path) {
                        let mut perms = metadata.permissions();
                        perms.set_mode(0o755); // rwxr-xr-x
                        let _ = std::fs::set_permissions(&pre_commit_path, perms);
                    }
                }

                println!("✅ pre-commit hook installed successfully at {:?}", pre_commit_path);
                println!("Scaffolded Ritsu environment successfully.");
            }
            _ => {
                eprintln!("Unknown command. Usage:\n  ritsud           (Starts MCP daemon)\n  ritsud check [f] (Audit files)\n  ritsud init      (Init hooks)");
                std::process::exit(1);
            }
        }
    } else {
        // Starts MCP Stdio Server Daemon
        let server = RpcServer::new(&project_root);
        if let Err(e) = server.run() {
            eprintln!("[ritsud-mcp] Server failed: {}", e);
            std::process::exit(1);
        }
    }
}
